name: new member added workfow
on:
  member:
    types: [added]

jobs:
  new_member_added:
    name: new member added job
    runs-on: ubuntu-latest
    steps:
      - name: run pwd
        run: pwd
      - name: run ls
        run: ls
      - name: run env
        run: env