name: new member added workfow
on:
  repository_dispatch:
    types: [org_member_change]

jobs:
  new_member_added:
    name: new member added job
    runs-on: ubuntu-latest
    steps:
      - name: cat payload file
        run: cat /home/runner/work/_temp/_github_workflow/event.json
#      - name: echo payload variable
#        run: echo ${{ payload }}
#      - name: echo if added
#        if: payload.action == 'added'
#        run: echo "the webhook action was added"
#      - name: echo if removed
#        if: payload.action == 'removed'
#        run: echo "the webhook action was removed"