name: new_user_registration
on:
  issues:
    types: [opened]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

jobs:
  new_member_registration:
    name: new registration invitation workflow
    if: github.event.label.name == 'newuserregistration'
    runs-on: ubuntu-latest
    steps:
      - name: update apt
        run: sudo apt update
      - name: install jq
        run: sudo apt install jq -y
      - name: install yq
        run: snap install yq -y
      - name: extract payload data from issue body
        run: |
          echo -e $(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.body' | sed 's/"//g' ) > /tmp/issuebody.yml
          cat /tmp/issuebody.yml
      - name: create environmental variable for requesting_user_id
        run: export requesting_user_id=$(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.user.id')
      - run: echo $requesting_user_id
      - run: cat /home/runner/work/_temp/_github_workflow/event.json