name: new_user_registration
on:
  issues:
    types: [unpinned]

jobs:
  new_member_registration:
      runs-on: ubuntu-latest
      steps:
        - name: 
          run: sudo apt update
        - name: install jq
          run: sudo apt install jq -y
        - name: install yq
          run: snap install yq -y
        - name: extract payload data from issue body
          run: echo -e $(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.body' | sed 's/"//g' ) > /tmp/issubody.txt
        - name: create environmental variable for requesting_user_id
          run: export requesting_user_id=$(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.user.id')