name: new_user_registration
on:
  workflow_dispatch:

jobs:
  new_member_registration:
    name: new registration invitation workflow
    runs-on: ubuntu-latest
    steps:
      - name: update apt
        run: sudo apt update
      - name: install jq
        run: sudo apt install jq -y
      - name: install yq
        run: sudo snap install yq
      - name: extract payload data from issue body
      - run: cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.user.id'