name: new_user_registration
on:
  issues:
    types: [opened]

jobs:
  new_member_registration:
    name: new registration invitation workflow
    runs-on: ubuntu-latest
    steps:
      - name: update apt
        run: sudo apt update
      - name: install jq
        run: sudo apt install jq -y
      - name: install yq
        run: sudo snap install yq
      - name: extract user id and set as requesting_user_id
        run: |
          echo $(echo requesting_user_id=$(echo $(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.user.id' ))) >> $GITHUB_ENV
      - name: verify requesting_user_id
        run: echo $requesting_user_id
      - name: extract org name and set as org_login
        run: |
          echo $(echo org_login=$(echo $(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.organization.login' | sed 's/"//g' ))) >> $GITHUB_ENV
      - name: verify org_login
        run: echo $org_login
      - name: curl orgteamregapicall.sh and make executable
        run: |
          curl https://modernapps.ninja/admin/orgteamregapicall.sh -o /tmp/orgteamregapicall.sh
          sudo chmod +x /tmp/orgteamregapicall.sh
      - name: make org and team invite api call
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.NINJABOTGURU }}
        run: /tmp/orgteamregapicall.sh
      - name: extract payload data from issue body
        run: |
          echo -e $(cat /home/runner/work/_temp/_github_workflow/event.json | jq '.issue.body' | sed 's/"//g' ) > /tmp/issuebody.yml
          cat /tmp/issuebody.yml
      - name: Print event content
        run: cat /home/runner/work/_temp/_github_workflow/event.json