name: testworkflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: cat payload file
        run: |
          
          while read i; do echo num=$i; done < $(echo willy)