name: testworkflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: set var FOO
      run: echo ::set-env name=FOO::$(echo -n "hello world")
    - name: verify var
      run: echo $FOO