name: testworkflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: set var FOO
      run: echo $(echo "FOO=$(echo "noodles")") >> $GITHUB_ENV
    - name: verify var
      run: echo $FOO >> /tmp/foofile.txt
    - name: verify foofile
      run: cat /tmp/foofile.txt