name: testworkflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    name: assign var
    env:
      NOOB: $(date)
    - name: check var
      run: echo $NOOB
    - name: list env
      run: env