name: testworkflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: cat payload file
        run: |
          echo line1 > willy.abs
          echo line2 >> willy.abs
          while read i; do echo num=$i; done < willy.abs